CREATE TABLE FLIGHT

(   FLIGHT_ID   INT NOT NULL AUTO_INCREMENT,
	QRTER		INT	NOT NULL,
	MNTH		INT	NOT NULL,
	DAY_OF_MONTH INT NOT NULL,
    DAY_OF_WEEK  INT NOT NULL,
    FL_DATE      DATE ,
    MKT_UNIQUE_CARRIER CHAR(15),
    PRIMARY KEY(FLIGHT_ID)
);

CREATE TABLE SEGMENT
(   SEGMENT_ID   INT NOT NULL AUTO_INCREMENT,
	ORIGIN		CHAR(55)	NOT NULL,
	ORIGIN_STATE_ABR	CHAR(55)	NOT NULL,
	DEST CHAR(55) NOT NULL,
    DEST_CITY_NAME  CHAR(55) NOT NULL,
    DEST_STATE_ABR  CHAR(55) NOT NULL,
	PRIMARY KEY (SEGMENT_ID),
    FOREIGN KEY (SEGMENT_ID) REFERENCES FLIGHT(FLIGHT_ID)
);

CREATE TABLE DELAY

(   DELAY_ID INT NOT NULL AUTO_INCREMENT,
    DEP_TIME INT NOT NULL,
    DEP_DELAY INT NOT NULL,
    CANCELLED INT NOT NULL,
    PRIMARY KEY (DELAY_ID),
    FOREIGN KEY (DELAY_ID) REFERENCES FLIGHT(FLIGHT_ID)
);
CREATE TABLE CAUSE

(   CAUSE_ID INT NOT NULL AUTO_INCREMENT,
    CARRIER_DELAY INT NOT NULL,
	WEATHER_DELAY INT NOT NULL,
    NAS_DELAY INT NOT NULL,
    SECURITY_DELAY INT NOT NULL,
    LATE_AIRCRAFT_DELAY INT NOT NULL,
    PRIMARY KEY (CAUSE_ID),
    FOREIGN KEY (CAUSE_ID) REFERENCES FLIGHT(FLIGHT_ID)
  );  
