CREATE TABLE Flightdelays

(   FLIGHT_ID   INT NOT NULL AUTO_INCREMENT,
	QRTER		INT	NOT NULL,
	MNTH		INT	NOT NULL,
	DAY_OF_MONTH INT NOT NULL,
    DAY_OF_WEEK  INT NOT NULL,
    FL_DATE      DATE ,
    MKT_UNIQUE_CARRIER CHAR(15),
	ORIGIN		CHAR(55)	NOT NULL,
    ORIGIN_CITY CHAR(55)    NOT NULL,
	ORIGIN_STATE_ABR	CHAR(55)	NOT NULL,
	DEST CHAR(55) NOT NULL,
    DEST_CITY_NAME  CHAR(55) NOT NULL,
    DEST_STATE_ABR  CHAR(55) NOT NULL,
    DEP_TIME INT NOT NULL,
    DEP_DELAY INT NOT NULL,
    CANCELLED INT NOT NULL,
    CARRIER_DELAY INT,
	WEATHER_DELAY INT,
    NAS_DELAY INT,
    SECURITY_DELAY INT,
    LATE_AIRCRAFT_DELAY INT,
	PRIMARY KEY(FLIGHT_ID)
  );  

